{% set name = "inquirer" %}
{% set version = "3.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inquirer-{{ version }}.tar.gz
  sha256: 958dbd5978f173630756a6ed6243acf931e750416eb7a6ed3a0ff13af0fdfcb5

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - blessed >=1.19.0
    - readchar >=3.0.6
    - python-editor >=1.0.4

test:
  imports:
    - inquirer
    - inquirer.render
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/magmax/python-inquirer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of common interactive command line user interfaces, based on Inquirer.js
  description: Collection of common interactive command line user interfaces, based on Inquirer.js.
  doc_url: https://python-inquirer.readthedocs.io/
  dev_url: https://github.com/magmax/python-inquirer

extra:
  recipe-maintainers:
    - mxr-conda
