{% set name = "inquirer" %}
{% set version = "2.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inquirer-{{ version }}.tar.gz
  sha256: e9876258183e24f6e8c44136b04f6f2e18dd6684aee59b86a8057c50601a6523

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry
  run:
    - blessed >=1.19.0
    - python >=3.7
    - python-editor >=1.0.4
    - readchar >=2.0.1
    - poetry

test:
  imports:
    - inquirer
    - inquirer.render
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/magmax/python-inquirer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of common interactive command line user interfaces, based on Inquirer.js

extra:
  recipe-maintainers:
    - mxr-conda
