{% set name = "inquirer" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inquirer-{{ version }}.tar.gz
  sha256: 60d169fddffe297e2f8ad54ab33698249ccfc3fc377dafb1e5cf01a0efb9cbe5

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - blessed >=1.19.0
    - readchar >=4.2.0
    - python-editor >=1.0.4
    - editor >=1.6.0

test:
  imports:
    - inquirer
    - inquirer.render
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/magmax/python-inquirer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of common interactive command line user interfaces, based on Inquirer.js
  description: Collection of common interactive command line user interfaces, based on Inquirer.js.
  doc_url: https://python-inquirer.readthedocs.io/
  dev_url: https://github.com/magmax/python-inquirer

extra:
  recipe-maintainers:
    - mxr-conda
